99_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

  root to: redirect('/cats')
end

99_cats/app/models/user.rb
class User < ApplicationRecord
  validates :user_name, :password_digest, :session_token, presence: true
  validates :user_name, :session_token, uniqueness: true
  validates :password, length: { in: (6..20), allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  has_many :cats,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :Cat

  has_many :cat_requests,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :CatRentalRequest

  has_many :tokens


  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    if @token
      session_tok = SessionToken.find_by(token: @token)
      SessionToken.create(user_id: self.id, token: SecureRandom.urlsafe_base64) if !session_tok
    else
      @token = SessionToken.create(user_id: self.id, token: SecureRandom.urlsafe_base64)
    end
  end

  def reset_session_token!
    token = SessionToken.find_by(token: session[:session_token])
    token.destroy
    token = SessionToken.new(user_id: self.id, token: SecureRandom.urlsafe_base64)
    return token.token
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    return nil if !user

    user.is_password?(password) ? user : nil
  end

end

99_cats/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      redirect_to cats_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end


  private

  def user_params
    params.require(:user).permit([:user_name, :password])
  end


end

99_cats/app/helpers/users_helper.rb
module UsersHelper
end

99_cats/app/views/users/new.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

<form class="" action=" <%= users_url %> " method="post">
  <input type = "hidden" name="authenticity_token" value ="<%= form_authenticity_token %>">

  <label for="user_name">Username:</label>
  <input id ="user_name" type="text" name="user[user_name]" value="">

  <label for="password">Password:</label>
  <input id ="password" type="password" name="user[password]" value="">

  <!-- <input type="button" name="" value="submit"> -->
  <button type="submit">Sign Up!</button>
</form>